export const dishes = [
  {
    name: "Spicy seasoned seafood noodles",
    price: 2.29,
    bowlsAvailable: 20,
    category: ["hot-dish", "soup"],
    imagePath: "Spicy-seasoned-seafood-noodles",
    type: "dine-in",
  },
  {
    name: "Salted Pasta with mushroom sauce",
    price: 2.69,
    bowlsAvailable: 11,
    category: ["soup", "cold-dish"],
    imagePath: "Salted-Pasta-with-mushroom-sauce",
    type: "to-go",
  },
  {
    name: "Beef dumpling in hot and sour soup",
    price: 2.99,
    bowlsAvailable: 16,
    category: ["soup", "appetizer"],
    imagePath: "Beef-dumpling-in-hot-and-sour-soup",
    type: "delivery",
  },
  {
    name: "Healthy noodle with spinach leaf",
    price: 3.29,
    bowlsAvailable: 22,
    category: ["grill", "cold-dish"],
    imagePath: "Healthy-noodle-with-spinach-leaf",
    type: "deliery",
  },
  {
    name: "Hot spicy fried rice with omelet",
    price: 3.49,
    bowlsAvailable: 13,
    category: ["cold-dish", "dessert"],
    imagePath: "Hot-spicy-fried-rice-with-omelet",
    type: "dine-in",
  },
  {
    name: "Spicy instant noodle with special omelette",
    price: 3.59,
    bowlsAvailable: 17,
    category: ["dessert", "grill"],
    imagePath: "Spicy-instant-noodle-with-special-omelette", ////////////
    type: "to-go",
  },
  {
    name: "Roasted chicken dinner platter delicious",
    price: 2.93,
    bowlsAvailable: 22,
    category: ["grill", "hot-dish"],
    imagePath: "Roasted-chicken-dinner-platter-delicious",
    type: "delivery",
  },
  {
    name: "Healthy pealthy boost good food",
    price: 5.49,
    bowlsAvailable: 13,
    category: ["cold-dish", "appetizer"],
    imagePath: "Healthy-pealthy-boost-good-food",
    type: "dine-in",
  },
  {
    name: "Chicken biryani halal food good indian plov",
    price: 4.19,
    bowlsAvailable: 17,
    category: ["hot-dish", "grill"],
    imagePath: "Chicken-biryani-halal-food-good-plov-indian",
    type: "to-go",
  },
  {
    name: "Crispy honey garlic chicken wings",
    price: 3.89,
    bowlsAvailable: 15,
    category: ["appetizer", "grill"],
    imagePath: "Crispy-honey-garlic-chicken-wings",
    type: "dine-in",
  },
  {
    name: "Vegetarian lasagna with cheesy layers",
    price: 4.59,
    bowlsAvailable: 12,
    category: ["hot-dish", "dessert"],
    imagePath: "Vegetarian-lasagna-with-cheesy-layers", ///////////////////////
    type: "delivery",
  },
  {
    name: "Thai green curry with coconut rice",
    price: 4.29,
    bowlsAvailable: 18,
    category: ["soup", "hot-dish"],
    imagePath: "Thai-green-curry-with-coconut-rice",
    type: "to-go",
  },
  {
    name: "Classic beef burger with fries combo",
    price: 3.79,
    bowlsAvailable: 25,
    category: ["grill", "appetizer"],
    imagePath: "Classic-beef-burger-with-fries-combo",
    type: "dine-in",
  },
  {
    name: "Cheesy garlic bread sticks platter",
    price: 2.19,
    bowlsAvailable: 19,
    category: ["appetizer", "cold-dish"],
    imagePath: "Cheesy-garlic-bread-sticks-platter",
    type: "delivery",
  },
  {
    name: "Sushi roll platter with wasabi sauce",
    price: 5.29,
    bowlsAvailable: 14,
    category: ["cold-dish", "grill"],
    imagePath: "Sushi-roll-platter-with-wasabi-sauce",
    type: "to-go",
  },
  {
    name: "Fresh garden salad with avocado dressing",
    price: 2.49,
    bowlsAvailable: 20,
    category: ["cold-dish", "appetizer"],
    imagePath: "Fresh-garden-salad-with-avocado-dressing",
    type: "dine-in",
  },
  {
    name: "Grilled lamb chops with mint sauce",
    price: 6.39,
    bowlsAvailable: 10,
    category: ["grill", "hot-dish"],
    imagePath: "Grilled-lamb-chops-with-mint-sauce",
    type: "delivery",
  },
  {
    name: "Tomato basil soup with crunchy croutons",
    price: 2.79,
    bowlsAvailable: 21,
    category: ["soup", "appetizer"],
    imagePath: "Tomato-basil-soup-with-crunchy-croutons",
    type: "to-go",
  },
  {
    name: "Pancake stack with maple syrup topping",
    price: 3.39,
    bowlsAvailable: 16,
    category: ["dessert", "cold-dish"],
    imagePath: "Pancake-stack-with-maple-syrup-topping",
    type: "dine-in",
  },
  {
    name: "Seafood paella rice with lemon garnish",
    price: 6.59,
    bowlsAvailable: 11,
    category: ["hot-dish", "grill"],
    imagePath: "Seafood-paella-rice-with-lemon-garnish",
    type: "delivery",
  },
  {
    name: "Falafel wrap with hummus sauce dip",
    price: 2.99,
    bowlsAvailable: 24,
    category: ["appetizer", "cold-dish"],
    imagePath: "Falafel-wrap-with-hummus-sauce-dip",
    type: "to-go",
  },
  {
    name: "Chocolate lava cake with ice cream scoop",
    price: 4.79,
    bowlsAvailable: 9,
    category: ["dessert", "cold-dish"],
    imagePath: "Chocolate-lava-cake-with-ice-cream-scoop", /////////////
    type: "dine-in",
  },
  {
    name: "Teriyaki salmon with steamed vegetables",
    price: 5.89,
    bowlsAvailable: 13,
    category: ["grill", "hot-dish"],
    imagePath: "Teriyaki-salmon-with-steamed-vegetables",
    type: "delivery",
  },
  {
    name: "Shawarma plate with garlic yogurt sauce",
    price: 3.69,
    bowlsAvailable: 18,
    category: ["grill", "hot-dish"],
    imagePath: "Shawarma-plate-with-garlic-yogurt-sauce",
    type: "to-go",
  },
];
